### ISSUE TITLE
Failed to go to next page of TIFF

### ISSUE THREAD

**Issue by ICouzinaki** [souliotisg/GSTools#3]
We get an exception when we try to go to next page. I have zipped and attached the TIFF file.
Exception is:
`>> Multi-File : false                                                                             >>
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at gr.gs.swing.components.imageview.helpers.LoggerHelper.logInputInfo(LoggerHelper.java:50)
	at gr.gs.swing.components.imageview.ImageViewer._internal_setActivePage(ImageViewer.java:904)
	at gr.gs.swing.components.imageview.ImageViewer.setActivePage(ImageViewer.java:867)
	at gr.gs.swing.components.imageview.ImageViewer$1.nextPagePressed(ImageViewer.java:168)
	at gr.gs.swing.components.imageview.IVController.goto_nextPage(IVController.java:483)
	at gr.gs.swing.components.imageview.IVController.access$000(IVController.java:21)
	at gr.gs.swing.components.imageview.IVController$1.actionPerformed(IVController.java:81)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2006)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2329)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:398)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:253)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:247)
	at java.awt.Component.processMouseEvent(Component.java:6301)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3278)
	at java.awt.Component.processEvent(Component.java:6066)
	at java.awt.Container.processEvent(Container.java:2052)
	at java.awt.Component.dispatchEventImpl(Component.java:4664)
	at java.awt.Container.dispatchEventImpl(Container.java:2110)
	at java.awt.Component.dispatchEvent(Component.java:4494)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4588)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4249)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4179)
	at java.awt.Container.dispatchEventImpl(Container.java:2096)
	at java.awt.Window.dispatchEventImpl(Window.java:2490)
	at java.awt.Component.dispatchEvent(Component.java:4494)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:652)
	at java.awt.EventQueue.access$000(EventQueue.java:95)
	at java.awt.EventQueue$1.run(EventQueue.java:613)
	at java.awt.EventQueue$1.run(EventQueue.java:611)
	at java.security.AccessController.doPrivileged(AccessController.java:226)
	at com.ibm.oti.security.CheckedAccessControlContext.securityCheck(CheckedAccessControlContext.java:35)
	at com.ibm.oti.security.CheckedAccessControlContext.securityCheck(CheckedAccessControlContext.java:39)
	at sun.misc.JavaSecurityAccessWrapper.doIntersectionPrivilege(JavaSecurityAccessWrapper.java:46)
	at java.awt.EventQueue$2.run(EventQueue.java:626)
	at java.awt.EventQueue$2.run(EventQueue.java:624)
	at java.security.AccessController.doPrivileged(AccessController.java:226)
	at com.ibm.oti.security.CheckedAccessControlContext.securityCheck(CheckedAccessControlContext.java:35)
	at sun.misc.JavaSecurityAccessWrapper.doIntersectionPrivilege(JavaSecurityAccessWrapper.java:41)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:623)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:280)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:195)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:185)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:180)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:172)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:133)

[abc.zip](https://github.com/souliotisg/GSTools/files/339024/abc.zip)
`

**Comment by souliotisg** [comment]
The problem is that you might not load the actual zip file. The reason for this conclusion is that in your log you have ">> Multi-File : false >>". This means that the application is in no Multi-file mode. I will check it anyway....

**Comment by souliotisg** [comment]
Fixed.

New version is released, 1.0.3.
